# frozen_string_literal: true

source 'https://rubygems.org'

gem 'rack', '~> 2.0.8'

gem 'env'
gem 'logger'
gem 'thin'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra-logger'

gem 'faraday'
gem 'faraday_middleware'

gem 'colorize'

gem 'jwt'
gem 'rethinkdb'

gem 'bcrypt'
