#!/usr/bin/env ruby

require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'tty-prompt'
end

CMDS = %i[rethinkdb nestjs angular]

mode = ARGV.empty? ? nil : CMDS[ARGV.first.to_i - 1]

if mode.nil?
  prompt = TTY::Prompt.new
  mode =
    prompt.select('What you want to run?') do |menu|
      CMDS.each { |choice| menu.choice choice }
    end
end

case mode.to_sym
when :rethinkdb
  system "cd #{__dir__}; rethinkdb"
when :angular
  system "cd #{__dir__}/angular; yarn dev"
when :nestjs
  system "cd #{__dir__}/nestjs; yarn start:dev"
else
  p mode
end
